# Generated by Django 2.0.6 on 2018-06-18 07:56

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('likes', models.IntegerField(default=0)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=50)),
                ('weekday_text', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CocktailType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('date', models.DateField(auto_now=True, verbose_name='Date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DrinkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('alcohol', models.FloatField(default=0)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DrunkyApp.Product')),
                ('cocktailType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DrunkyApp.CocktailType')),
            ],
            bases=('DrunkyApp.product',),
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DrunkyApp.Product')),
                ('drinkType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DrunkyApp.DrinkType')),
            ],
            bases=('DrunkyApp.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='comments',
            field=models.ManyToManyField(to='DrunkyApp.Comment'),
        ),
        migrations.AddField(
            model_name='product',
            name='dishes',
            field=models.ManyToManyField(to='DrunkyApp.Dish'),
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(to='DrunkyApp.Image'),
        ),
        migrations.AddField(
            model_name='bar',
            name='comments',
            field=models.ManyToManyField(to='DrunkyApp.Comment'),
        ),
        migrations.AddField(
            model_name='bar',
            name='images',
            field=models.ManyToManyField(to='DrunkyApp.Image'),
        ),
        migrations.AddField(
            model_name='account',
            name='favouriteBars',
            field=models.ManyToManyField(default=None, null=True, to='DrunkyApp.Bar'),
        ),
        migrations.AddField(
            model_name='account',
            name='photo',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='DrunkyApp.Image'),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='drinks',
            field=models.ManyToManyField(to='DrunkyApp.Drink'),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='ingredients',
            field=models.ManyToManyField(to='DrunkyApp.Ingredient'),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='tools',
            field=models.ManyToManyField(to='DrunkyApp.Tool'),
        ),
        migrations.AddField(
            model_name='account',
            name='favouriteCocktails',
            field=models.ManyToManyField(default=None, null=True, to='DrunkyApp.Cocktail'),
        ),
        migrations.AddField(
            model_name='account',
            name='favouriteDrinks',
            field=models.ManyToManyField(default=None, null=True, to='DrunkyApp.Drink'),
        ),
    ]
