# Generated by Django 2.0.6 on 2018-06-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrunkyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='favouriteBars',
            field=models.ManyToManyField(blank=True, default=None, to='DrunkyApp.Bar'),
        ),
        migrations.AlterField(
            model_name='account',
            name='favouriteCocktails',
            field=models.ManyToManyField(blank=True, default=None, to='DrunkyApp.Cocktail'),
        ),
        migrations.AlterField(
            model_name='account',
            name='favouriteDrinks',
            field=models.ManyToManyField(blank=True, default=None, to='DrunkyApp.Drink'),
        ),
        migrations.AlterField(
            model_name='bar',
            name='comments',
            field=models.ManyToManyField(blank=True, to='DrunkyApp.Comment'),
        ),
        migrations.AlterField(
            model_name='product',
            name='comments',
            field=models.ManyToManyField(blank=True, to='DrunkyApp.Comment'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dishes',
            field=models.ManyToManyField(blank=True, to='DrunkyApp.Dish'),
        ),
    ]
