# Generated by Django 2.0.6 on 2018-06-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrunkyApp', '0003_auto_20180620_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
