# Generated by Django 2.0.5 on 2018-06-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrunkyApp', '0003_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('likes', models.IntegerField(default=0)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=50)),
                ('weekday_text', models.CharField(max_length=500)),
                ('comments', models.ManyToManyField(to='DrunkyApp.Comment')),
                ('images', models.ManyToManyField(to='DrunkyApp.Image')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='favouriteCocktails',
            field=models.ManyToManyField(to='DrunkyApp.Cocktail'),
        ),
        migrations.AddField(
            model_name='account',
            name='favouriteDrinks',
            field=models.ManyToManyField(to='DrunkyApp.Drink'),
        ),
        migrations.AddField(
            model_name='account',
            name='favouriteBars',
            field=models.ManyToManyField(to='DrunkyApp.Bar'),
        ),
    ]
