# Generated by Django 2.0.7 on 2018-09-10 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DrunkyApp', '0006_auto_20180910_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commenttoaccount',
            name='account',
        ),
        migrations.AddField(
            model_name='commenttoaccount',
            name='account',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='DrunkyApp.Account'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='commenttoaccount',
            name='comment',
        ),
        migrations.AddField(
            model_name='commenttoaccount',
            name='comment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='DrunkyApp.Comment'),
            preserve_default=False,
        ),
    ]
