# Generated by Django 2.0.7 on 2018-09-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrunkyApp', '0007_auto_20180910_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='likedBars',
            field=models.ManyToManyField(blank=True, default=None, related_name='liked_bars', to='DrunkyApp.Bar'),
        ),
        migrations.AddField(
            model_name='account',
            name='likedCocktails',
            field=models.ManyToManyField(blank=True, default=None, related_name='liked_cocktails', to='DrunkyApp.Cocktail'),
        ),
        migrations.AddField(
            model_name='account',
            name='likedDrinks',
            field=models.ManyToManyField(blank=True, default=None, related_name='liked_drinks', to='DrunkyApp.Drink'),
        ),
        migrations.AlterField(
            model_name='account',
            name='favouriteBars',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite_bars', to='DrunkyApp.Bar'),
        ),
        migrations.AlterField(
            model_name='account',
            name='favouriteCocktails',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite_cocktails', to='DrunkyApp.Cocktail'),
        ),
        migrations.AlterField(
            model_name='account',
            name='favouriteDrinks',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite_drinks', to='DrunkyApp.Drink'),
        ),
    ]
