# Generated by Django 2.0.7 on 2018-10-15 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DrunkyApp', '0009_cocktail_drinkstype'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktailtype',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DrunkyApp.Image'),
        ),
        migrations.AddField(
            model_name='country',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DrunkyApp.Image'),
        ),
        migrations.AddField(
            model_name='drinktype',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DrunkyApp.Image'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DrunkyApp.Image'),
        ),
        migrations.AddField(
            model_name='tool',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DrunkyApp.Image'),
        ),
    ]
