# Generated by Django 2.0.7 on 2018-10-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrunkyApp', '0010_auto_20181015_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='drinks',
            field=models.ManyToManyField(blank=True, to='DrunkyApp.Drink'),
        ),
    ]
