# Generated by Django 2.0.7 on 2018-10-16 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DrunkyApp', '0011_auto_20181015_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DrunkyApp.Drink')),
            ],
        ),
        migrations.CreateModel(
            name='DrinkTypeMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('drinksType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DrunkyApp.DrinkType')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DrunkyApp.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='MeasureType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='drinks',
            field=models.ManyToManyField(blank=True, to='DrunkyApp.DrinkMeasure'),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='drinksType',
            field=models.ManyToManyField(blank=True, to='DrunkyApp.DrinkTypeMeasure'),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='DrunkyApp.IngredientMeasure'),
        ),
        migrations.AddField(
            model_name='ingredientmeasure',
            name='measureType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DrunkyApp.MeasureType'),
        ),
        migrations.AddField(
            model_name='drinktypemeasure',
            name='measureType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DrunkyApp.MeasureType'),
        ),
        migrations.AddField(
            model_name='drinkmeasure',
            name='measureType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DrunkyApp.MeasureType'),
        ),
    ]
